export const EVENT_ID = 'social-circle-2026';

const courts = {
  1: [
    { round: 1, time: '11:00 AM', teamA: ['Ritika Kandhari', 'Jacob Thomas'], teamB: ['Chanchal Jaising', 'Omar'] },
    { round: 2, time: '11:08 AM', teamA: ['Sanjana Ramesh', 'Rahul Satish'], teamB: ['Aaira Sood', 'Arjun Raju'] },
    { round: 3, time: '11:16 AM', teamA: ['Mary Jose', 'Akhil'], teamB: ['Mira Mahadevan', 'Akshay Mari'] },
    { round: 4, time: '11:24 AM', teamA: ['Malvika Ramesh', 'Ashish Moses'], teamB: ['Sushmita Solanki', 'Tushar Dhohdy'] },
    { round: 5, time: '11:32 AM', teamA: ['Banie', 'Akhil'], teamB: ['Mary Jose', 'Nikhil Menda'] },
    { round: 6, time: '11:40 AM', teamA: ['Chanchal Jaising', 'Ashish Moses'], teamB: ['Malvika Ramesh', 'Omar'] },
    { round: 7, time: '11:48 AM', teamA: ['Banie', 'Nikhil Menda'], teamB: ['Aaira Sood', 'Chirag Sen'] },
    { round: 8, time: '11:56 AM', teamA: ['Nikita George', 'Ashish Moses'], teamB: ['Chanchal Jaising', 'Abran Fareed'] },
    { round: 9, time: '12:04 PM', teamA: ['Aaira Sood', 'Nikhil Menda'], teamB: ['Sushmita Solanki', 'Arjun Raju'] },
    { round: 10, time: '12:12 PM', teamA: ['Malvika Ramesh', 'Abran Fareed'], teamB: ['Harini Satish', 'Chirag Sen'] },
    { round: 11, time: '12:20 PM', teamA: ['Sushmita Solanki', 'Nikhil Menda'], teamB: ['Jharna', 'Prashanth Ponappa'] },
    { round: 12, time: '12:28 PM', teamA: ['Mary Jose', 'Omar'], teamB: ['Harini Satish', 'Abran Fareed'] },
    { round: 13, time: '12:36 PM', teamA: ['Aaira Sood', 'Prashanth Ponappa'], teamB: ['Malvika Ramesh', 'Bhargav Gopal'] },
    { round: 14, time: '12:44 PM', teamA: ['Harini Satish', 'Nikhil Menda'], teamB: ['Bhavya Mandana', 'Akshay Mari'] },
    { round: 15, time: '12:52 PM', teamA: ['Sushmita Solanki', 'Bhargav Gopal'], teamB: ['Chanchal Jaising', 'Jacob Thomas'] },
    { round: 16, time: '1:00 PM', teamA: ['Sanjana Ramesh', 'Nikhil Menda'], teamB: ['Mary Jose', 'Pawan'] },
    { round: 17, time: '1:08 PM', teamA: ['Ritika Kandhari', 'Bhargav Gopal'], teamB: ['Archana Gowda', 'Nihal Thomas'] },
    { round: 18, time: '1:16 PM', teamA: ['Banie', 'Akshay Mari'], teamB: ['Ann Sankey', 'Arjun Raju'] },
    { round: 19, time: '1:24 PM', teamA: ['Nikita George', 'Cheeku'], teamB: ['Harini Satish', 'Omar'] },
    { round: 20, time: '1:32 PM', teamA: ['Mira Mahadevan', 'Nikhil Menda'], teamB: ['Ann Sankey', 'Bhargav Gopal'] },
  ],
  2: [
    { round: 1, time: '11:00 AM', teamA: ['Naba', 'Nihal Thomas'], teamB: ['Nikita George', 'Abran Fareed'] },
    { round: 2, time: '11:08 AM', teamA: ['Ann Sankey', 'Tushar Dhohdy'], teamB: ['Sushmita Solanki', 'Prashanth Ponappa'] },
    { round: 3, time: '11:16 AM', teamA: ['Nikita George', 'Nihal Thomas'], teamB: ['Harini Satish', 'Suraj'] },
    { round: 4, time: '11:24 AM', teamA: ['Ann Sankey', 'Prashanth Ponappa'], teamB: ['Jharna', 'Nikash'] },
    { round: 5, time: '11:32 AM', teamA: ['Sanjana Ramesh', 'Akshay Mari'], teamB: ['Mira Mahadevan', 'Rahul Satish'] },
    { round: 6, time: '11:40 AM', teamA: ['Rahael Wilson', 'Nikash'], teamB: ['Neha JP', 'Sachid'] },
    { round: 7, time: '11:48 AM', teamA: ['Sanjana Ramesh', 'Arjun Raju'], teamB: ['Ann Sankey', 'Akhil'] },
    { round: 8, time: '11:56 AM', teamA: ['Malvika Ramesh', 'Sachid'], teamB: ['Ritika Kandhari', 'Omar'] },
    { round: 9, time: '12:04 PM', teamA: ['Banie', 'Prashanth Ponappa'], teamB: ['Mira Mahadevan', 'Akhil'] },
    { round: 10, time: '12:12 PM', teamA: ['Nikita George', 'Pawan'], teamB: ['Ritika Kandhari', 'Ashish Moses'] },
    { round: 11, time: '12:20 PM', teamA: ['Banie', 'Arjun Raju'], teamB: ['Rahael Wilson', 'Bhargav Gopal'] },
    { round: 12, time: '12:28 PM', teamA: ['Chanchal Jaising', 'Akhil'], teamB: ['Samanvita', 'Nihal Thomas'] },
    { round: 13, time: '12:36 PM', teamA: ['Archana Gowda', 'Arjun Raju'], teamB: ['Sushmita Solanki', 'Nikash'] },
    { round: 14, time: '12:44 PM', teamA: ['Banie', 'Abran Fareed'], teamB: ['Samanvita', 'Suraj'] },
    { round: 15, time: '12:52 PM', teamA: ['Malvika Ramesh', 'Prashanth Ponappa'], teamB: ['Neha JP', 'Cheeku'] },
    { round: 16, time: '1:00 PM', teamA: ['Harini Satish', 'Akshay Mari'], teamB: ['Banie', 'Philip Mathew'] },
    { round: 17, time: '1:08 PM', teamA: ['Malvika Ramesh', 'Cheeku'], teamB: ['Jharna', 'Jacob Thomas'] },
    { round: 18, time: '1:16 PM', teamA: ['Mira Mahadevan', 'Prashanth Ponappa'], teamB: ['Aaira Sood', 'Philip Mathew'] },
    { round: 19, time: '1:24 PM', teamA: ['Archana Gowda', 'Ashish Moses'], teamB: ['Malvika Ramesh', 'Jacob Thomas'] },
    { round: 20, time: '1:32 PM', teamA: ['Sushmita Solanki', 'Akshay Mari'], teamB: ['Neha JP', 'Rahul Satish'] },
  ],
  3: [
    { round: 1, time: '11:00 AM', teamA: ['Erika Joseph', 'Suraj'], teamB: ['Harini Satish', 'Pawan'] },
    { round: 2, time: '11:08 AM', teamA: ['Neha JP', 'Nikash'], teamB: ['Jharna', 'Bhargav Gopal'] },
    { round: 3, time: '11:16 AM', teamA: ['Naba', 'Abran Fareed'], teamB: ['Erika Joseph', 'Pawan'] },
    { round: 4, time: '11:24 AM', teamA: ['Neha JP', 'Bhargav Gopal'], teamB: ['Archana Gowda', 'Sachid'] },
    { round: 5, time: '11:32 AM', teamA: ['Bhavya Mandana', 'Suraj'], teamB: ['Erika Joseph', 'Chirag Sen'] },
    { round: 6, time: '11:40 AM', teamA: ['Archana Gowda', 'Bhargav Gopal'], teamB: ['Jharna', 'Cheeku'] },
    { round: 7, time: '11:48 AM', teamA: ['Mary Jose', 'Akshay Mari'], teamB: ['Bhavya Mandana', 'Tushar Dhohdy'] },
    { round: 8, time: '11:56 AM', teamA: ['Rahael Wilson', 'Cheeku'], teamB: ['Erika Joseph', 'Nihal Thomas'] },
    { round: 9, time: '12:04 PM', teamA: ['Mary Jose', 'Rahul Satish'], teamB: ['Ann Sankey', 'Nikash'] },
    { round: 10, time: '12:12 PM', teamA: ['Naba', 'Omar'], teamB: ['Chanchal Jaising', 'Suraj'] },
    { round: 11, time: '12:20 PM', teamA: ['Aaira Sood', 'Rahul Satish'], teamB: ['Neha JP', 'Tushar Dhohdy'] },
    { round: 12, time: '12:28 PM', teamA: ['Nikita George', 'Suraj'], teamB: ['Bhavya Mandana', 'Pawan'] },
    { round: 13, time: '12:36 PM', teamA: ['Ann Sankey', 'Cheeku'], teamB: ['Neha JP', 'Ashish Moses'] },
    { round: 14, time: '12:44 PM', teamA: ['Nikita George', 'Philip Mathew'], teamB: ['Erika Joseph', 'Akhil'] },
    { round: 15, time: '12:52 PM', teamA: ['Jharna', 'Ashish Moses'], teamB: ['Ritika Kandhari', 'Sachid'] },
    { round: 16, time: '1:00 PM', teamA: ['Aaira Sood', 'Akhil'], teamB: ['Bhavya Mandana', 'Rahul Satish'] },
    { round: 17, time: '1:08 PM', teamA: ['Naba', 'Ashish Moses'], teamB: ['Rahael Wilson', 'Abran Fareed'] },
    { round: 18, time: '1:16 PM', teamA: ['Sushmita Solanki', 'Rahul Satish'], teamB: ['Samanvita', 'Nikhil Menda'] },
    { round: 19, time: '1:24 PM', teamA: ['Chanchal Jaising', 'Nihal Thomas'], teamB: ['Erika Joseph', 'Abran Fareed'] },
    { round: 20, time: '1:32 PM', teamA: ['Aaira Sood', 'Tushar Dhohdy'], teamB: ['Banie', 'Nikash'] },
  ],
  4: [
    { round: 1, time: '11:00 AM', teamA: ['Bhavya Mandana', 'Chirag Sen'], teamB: ['Samanvita', 'Philip Mathew'] },
    { round: 2, time: '11:08 AM', teamA: ['Rahael Wilson', 'Sachid'], teamB: ['Archana Gowda', 'Cheeku'] },
    { round: 3, time: '11:16 AM', teamA: ['Samanvita', 'Chirag Sen'], teamB: ['Bhavya Mandana', 'Philip Mathew'] },
    { round: 4, time: '11:24 AM', teamA: ['Ritika Kandhari', 'Cheeku'], teamB: ['Rahael Wilson', 'Jacob Thomas'] },
    { round: 5, time: '11:32 AM', teamA: ['Samanvita', 'Pawan'], teamB: ['Harini Satish', 'Philip Mathew'] },
    { round: 6, time: '11:40 AM', teamA: ['Naba', 'Jacob Thomas'], teamB: ['Ritika Kandhari', 'Nihal Thomas'] },
    { round: 7, time: '11:48 AM', teamA: ['Samanvita', 'Rahul Satish'], teamB: ['Mira Mahadevan', 'Philip Mathew'] },
    { round: 8, time: '11:56 AM', teamA: ['Archana Gowda', 'Jacob Thomas'], teamB: ['Naba', 'Suraj'] },
    { round: 9, time: '12:04 PM', teamA: ['Neha JP', 'Akshay Mari'], teamB: ['Sanjana Ramesh', 'Tushar Dhohdy'] },
    { round: 10, time: '12:12 PM', teamA: ['Erika Joseph', 'Jacob Thomas'], teamB: ['Bhavya Mandana', 'Nihal Thomas'] },
    { round: 11, time: '12:20 PM', teamA: ['Sanjana Ramesh', 'Nikash'], teamB: ['Ann Sankey', 'Sachid'] },
    { round: 12, time: '12:28 PM', teamA: ['Erika Joseph', 'Philip Mathew'], teamB: ['Naba', 'Chirag Sen'] },
    { round: 13, time: '12:36 PM', teamA: ['Jharna', 'Sachid'], teamB: ['Rahael Wilson', 'Tushar Dhohdy'] },
    { round: 14, time: '12:44 PM', teamA: ['Mira Mahadevan', 'Pawan'], teamB: ['Mary Jose', 'Chirag Sen'] },
    { round: 15, time: '12:52 PM', teamA: ['Archana Gowda', 'Nikash'], teamB: ['Rahael Wilson', 'Omar'] },
    { round: 16, time: '1:00 PM', teamA: ['Samanvita', 'Arjun Raju'], teamB: ['Mira Mahadevan', 'Chirag Sen'] },
    { round: 17, time: '1:08 PM', teamA: ['Nikita George', 'Omar'], teamB: ['Chanchal Jaising', 'Sachid'] },
    { round: 18, time: '1:16 PM', teamA: ['Sanjana Ramesh', 'Akhil'], teamB: ['Mary Jose', 'Tushar Dhohdy'] },
    { round: 19, time: '1:24 PM', teamA: ['Ritika Kandhari', 'Suraj'], teamB: ['Naba', 'Pawan'] },
    { round: 20, time: '1:32 PM', teamA: ['Jharna', 'Arjun Raju'], teamB: ['Sanjana Ramesh', 'Prashanth Ponappa'] },
  ],
};

export const FIXTURES = Object.entries(courts).flatMap(([court, matches]) =>
  matches.map((match) => ({
    id: `court${court}_round${match.round}`,
    court: Number(court),
    round: match.round,
    scheduledTime: match.time,
    teamA: match.teamA,
    teamB: match.teamB,
  })),
);
